fix yaml script nesting bug

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -19,25 +19,24 @@ jobs:
           username: ec2-user
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
-            script: |
-              cd pixify
+            cd pixify
 
-              git pull
+            git pull
 
-              cd server
-              docker stop $(docker ps -q) || true
-              docker rm $(docker ps -aq) || true
-              docker build -t pixify-backend .
-              docker run -d -p 4005:4005 --restart always pixify-backend
+            cd server
+            docker stop $(docker ps -q) || true
+            docker rm $(docker ps -aq) || true
+            docker build -t pixify-backend .
+            docker run -d -p 4005:4005 --restart always pixify-backend
 
 
-              cd ../client
-              npm install
-              npm run build
-              if [ -d "dist" ]; then
-                sudo rm -rf /usr/share/nginx/html/*
-                sudo cp -r dist/* /usr/share/nginx/html/
-                sudo systemctl restart nginx
-              else
-                echo "Build failed, skipping deploy"
-              fi
+            cd ../client
+            npm install
+            npm run build
+            if [ -d "dist" ]; then
+              sudo rm -rf /usr/share/nginx/html/*
+              sudo cp -r dist/* /usr/share/nginx/html/
+              sudo systemctl restart nginx
+            else
+              echo "Build failed, skipping deploy"
+            fi
